Added basic management operations.
Sobek-W-A/edt-manager-backend pull request #25
Opened 2024-10-16 12:29 UTC by Maximelego

Added database Initialization.
Added Redis manager for tokens.
Added Basic routers.
Added basic enumerations for HTTP Exceptions.

All models are subject to change about their data. The only useful ones are login and hash.
Added basic authentication methods.
Updated docker containers. **You will need to rebuild the project !**

2024-10-18 07:56 UTC, desaleo requested changes
A lot of un-typed/miss-typed values (I've commented every one i've seen but I may have missed some especially in function body) I highly recommand using pyright as a type checker in strict mode.

2024-10-18 07:56 UTC, desaleo commented on app/main.py
> +tags_metadata = [
should be typed with list[dict[str, str]] or using TypedDict

2024-10-18 07:56 UTC, desaleo commented on app/main.py
> +app = FastAPI(title="SOBEK W.A. API",
should be type with FastAPI object

2024-10-18 07:56 UTC, desaleo commented on app/main.py
> +origins = [
should be typed with list[str]

2024-10-18 07:56 UTC, desaleo commented on app/main.py
> +async def startup():
should be typed (return type: None)

2024-10-18 07:56 UTC, desaleo commented on app/main.py
> +async def root():
should be typed

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
should be typed

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +    def generate(self, user_id: int):
should be typed (return type: None)

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +    async def revoke(self, redis_db: redis.Redis = Redis.get_redis()):
should be typed with Awaitable[\<ReturnType>] or Coroutine[\<YieldType>, \<SendType>, \<ReturnType>]

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +    async def extract_payload(self):
should be typed with Awaitable[<ReturnType>] or Coroutine[<YieldType>, <SendType>, <ReturnType>]

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +    async def is_revoked(self, redis_db: redis.Redis = Redis.get_redis()):
should be typed with Awaitable[<ReturnType>] or Coroutine[<YieldType>, <SendType>, <ReturnType>]

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +    def get_tokens_in_response(self):
should be typed using dict[] or TypedDict

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +    async def refresh_tokens(self) -> None:
should be typed with Awaitable[<ReturnType>] or Coroutine[<YieldType>, <SendType>, <ReturnType>]

2024-10-18 07:56 UTC, desaleo commented on app/models/pydantic/TokenModel.py
> +    def export_pydantic_to_model(self, attributes: TokenAttributes | None = None):
should be typed (return type)

2024-10-18 07:56 UTC, desaleo commented on app/models/pydantic/TokenModel.py
> +    def export_pydantic_to_model(self, attributes: TokenAttributes | None = None):
should be typed (return type)

2024-10-18 07:56 UTC, desaleo commented on app/models/pydantic/TokenModel.py
> +    def export_pydantic_to_model(self, attributes: TokenAttributes | None = None):
should be typed (return type)

2024-10-18 07:56 UTC, desaleo commented on app/models/tortoise/user.py
> +pwd_context   = CryptContext(schemes=["bcrypt"], deprecated="auto")
should be typed and the line below as well

2024-10-18 07:56 UTC, desaleo commented on app/models/tortoise/user.py
> +    def __str__(self):
should be typed (return type: str)

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +            raise Exception("No expire time was provided inside the .env file !")
should use a more precise exception class, even better: a custom one

2024-10-18 07:56 UTC, desaleo commented on app/models/Tokens.py
> +            raise Exception("No secrets were provided inside the .env file !")
should use a more precise exception class, even better: a custom one

2024-10-18 07:56 UTC, desaleo commented on app/models/tortoise/user.py
> +    async def authenticate_user(login: str, password: str) -> Optional["UserInDB"] :
should be typed with Awaitable[<ReturnType>] or Coroutine[<YieldType>, <SendType>, <ReturnType>]

2024-10-18 07:56 UTC, desaleo commented on app/models/tortoise/user.py
> +        return "[INFO] - USER " + self.login + " ID : " + str(self.id)
should use f-string instead like `` f"[INFO] - USER {self.login} ID : {self.id}"``

2024-10-18 07:56 UTC, desaleo commented on app/routes/auth.py
> +authRouter = APIRouter()
should be typed

2024-10-18 07:56 UTC, desaleo commented on app/routes/user.py
> +userRouter = APIRouter()
should be typed

2024-10-18 07:56 UTC, desaleo commented on app/utils/databases/datasets.py
> +async def load_dummy_datasets():
should be typed

2024-10-18 07:56 UTC, desaleo commented on app/utils/databases/db.py
> +async def startup_databases(app: FastAPI):
should be typed

2024-10-18 07:56 UTC, desaleo commented on app/utils/databases/redis.py
> +    async def load_redis(cls):
should be typed (return type: None)

2024-10-18 07:56 UTC, desaleo commented on app/utils/databases/postgresql.py
> +    async def init_postgres_db(app: FastAPI) -> None:
should be typed with Awaitable[<ReturnType>] or Coroutine[<YieldType>, <SendType>, <ReturnType>]

2024-10-18 07:56 UTC, desaleo commented on app/utils/databases/postgresql.py
> +    def get_available_models():
should be typed

2024-10-18 07:56 UTC, desaleo commented on app/utils/databases/redis.py
> +    def get_redis(cls):
should be typed

2024-10-21 14:32 UTC, HugoBien approved these changes
Great work !

2024-10-21 14:33 UTC, desaleo approved these changes
LGTM

2024-10-21 14:33 UTC, merged