23 add the authentication routes
Sobek-W-A/edt-manager-backend pull request #26
Opened 2024-10-17 14:01 UTC by Maximelego

Added 3 routes : 

POST /auth/login : which logs the user.
POST /auth/logout : which disconnects the user.
POST /auth/refresh : which refreshes the user's tokens.

This branch is based on #24 branch to manage basic database information and authentication.

2024-10-22 09:26 UTC, desaleo requested changes

2024-10-22 09:26 UTC, desaleo commented on app/models/Tokens.py
reverse this changes and keep the quotes to avoid crash on windows

2024-10-23 06:35 UTC, desaleo approved these changes
LGTM

2024-10-23 06:38 UTC, HugoBien approved these changes
Bien !

2024-10-23 06:38 UTC, merged